import requests
import json
import datetime
import sys
import urllib3
import csv

# Suppress insecure request warnings generated by verify=False
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def main():
    # 1. Authentication
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    ctd_ip = input("Enter CTD IP or hostname: ").strip()
    username = input("Enter CTD username: ").strip()
    password = input("Enter CTD password: ").strip()

    auth_payload = {"username": username, "password": password}
    
    try:
        doauth = requests.post(f"https://{ctd_ip}/auth/authenticate", verify=False, json=auth_payload)
        
        try:
            auth_data = doauth.json()
        except ValueError:
            print("Authentication Failed: The server did not return valid JSON.")
            sys.exit(1)
            
    except requests.exceptions.RequestException as e:
        print(f"Failed to connect to the server: {e}")
        sys.exit(1)

    if "error" in auth_data:
        print("Authentication Failed:", auth_data['error'])
        sys.exit(1)
        
    token = auth_data.get('token')
    if not token:
        print("Authentication Failed: No token returned by the server.")
        sys.exit(1)

    headers = {
        'Authorization': token,
        'Content-Type': 'application/json'
    }


    # 2. Fetch All Data (Handling Pagination)
    edge_host_id = input("Enter the Edge Host ID: ").strip()
    
    all_installed_programs = []
    page = 1
    per_page = 50 
    
    while True:
        endpoint = f"/ranger/ranger_api/asset_installed_programs?fields=name,;$version,;$vendor&sort=name&page={page}&per_page={per_page}&asset_rid__exact={edge_host_id}"
        url = f"https://{ctd_ip}{endpoint}"
        
        try:
            response = requests.get(url, headers=headers, verify=False)
            response.raise_for_status()
            
            data = response.json()
            objects = data.get("objects", [])
            all_installed_programs.extend(objects)
            
            if len(objects) < per_page:
                break
                
            page += 1
            
        except requests.exceptions.RequestException:
            break
        except ValueError:
            break

    # 3. Export to CSV

    filename = f"windows_programs_list_{timestamp}.csv"
    
    try:
        with open(filename, mode='w', newline='', encoding='utf-8') as csv_file:
            writer = csv.writer(csv_file)
            
            # Write the header row
            writer.writerow(['program', 'vendor', 'version'])
            
            # Write the data rows
            for obj in all_installed_programs:
                # use .get() and check both the raw string and standard string just in case the API strips the ';$' prefix from the returned JSON keys
                program = obj.get('name', '')
                vendor = obj.get(';$vendor', obj.get('vendor', ''))
                version = obj.get(';$version', obj.get('version', ''))
                
                writer.writerow([program, vendor, version])
    except Exception as e:
        print(f"Failed to write to CSV: {e}")
        sys.exit(1)

    # 4. Terminal Output
    # This is the only output printed to the terminal after inputs
    print(f"Total programs found: {len(all_installed_programs)}")

if __name__ == "__main__":
    main()


